Lang:

  # Defines the plugin language
  lang: en_us

  # Defines whether the client language should be used, if it is available
  client-lang: true



Options:

  # Defines whether the plugin should notify when a new version is available
  check-for-update: true

  # Defines the default space between the top part of two rows
  space-between-lines: 0.26

  Link:

    # Defines whether the PlaceholderAPI link should be active
    placeholder-api: true



  # Defines a list of Unicode symbols to be converted within holo rows
  Symbols:

    "[X]": "\u2588"
    "[|]": "\u23B9"