name: GHolo
version: 1.0.5
description: Create Holos with modern Technology, great Performance and Animations!
author: Gecolay
website: https://www.spigotmc.org/resources/70913
main: dev.geco.gholo.GHoloMain
api-version: 1.13
softdepend: [PlaceholderAPI]

commands:

  gholo:

    usage: /<command>
    aliases: [holo]
    description: Holo-Main-Command
    permission: GHolo.Holo

  gholoreload:

    usage: /<command>
    aliases: [gholorl]
    description: GHolo-Config-Reload
    permission: GHolo.GHoloReload



permissions:

  GHolo.*:
    default: op
    description: OP-Permission for all Commands and Functions for GHolo

  GHolo.Holo:
    default: op
    description: Main-Holo | Permission

  GHolo.Update:
    default: op
    description: Get-Update-Notification | Permission

  GHolo.GHoloReload:
    default: op
    description: Config-Reload-Command | Permission